import { MD3LightTheme, MD3DarkTheme, configureFonts, useTheme } from 'react-native-paper';

const fontConfig = {
  displayLarge: { fontFamily: 'System', fontSize: 57, fontWeight: '400' as const, letterSpacing: 0 },
  displayMedium: { fontFamily: 'System', fontSize: 45, fontWeight: '400' as const, letterSpacing: 0 },
  displaySmall: { fontFamily: 'System', fontSize: 36, fontWeight: '400' as const, letterSpacing: 0 },
  headlineLarge: { fontFamily: 'System', fontSize: 32, fontWeight: '400' as const, letterSpacing: 0 },
  headlineMedium: { fontFamily: 'System', fontSize: 28, fontWeight: '400' as const, letterSpacing: 0 },
  headlineSmall: { fontFamily: 'System', fontSize: 24, fontWeight: '400' as const, letterSpacing: 0 },
  titleLarge: { fontFamily: 'System', fontSize: 22, fontWeight: '500' as const, letterSpacing: 0 },
  titleMedium: { fontFamily: 'System', fontSize: 16, fontWeight: '500' as const, letterSpacing: 0.15 },
  titleSmall: { fontFamily: 'System', fontSize: 14, fontWeight: '500' as const, letterSpacing: 0.1 },
  bodyLarge: { fontFamily: 'System', fontSize: 16, fontWeight: '400' as const, letterSpacing: 0.5 },
  bodyMedium: { fontFamily: 'System', fontSize: 14, fontWeight: '400' as const, letterSpacing: 0.25 },
  bodySmall: { fontFamily: 'System', fontSize: 12, fontWeight: '400' as const, letterSpacing: 0.4 },
  labelLarge: { fontFamily: 'System', fontSize: 14, fontWeight: '500' as const, letterSpacing: 0.1 },
  labelMedium: { fontFamily: 'System', fontSize: 12, fontWeight: '500' as const, letterSpacing: 0.5 },
  labelSmall: { fontFamily: 'System', fontSize: 11, fontWeight: '500' as const, letterSpacing: 0.5 },
};

const fonts = configureFonts({ config: fontConfig });

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    // Nordic-Professional primary: Indigo
    primary: '#6366F1',
    primaryContainer: '#E0E7FF',
    secondary: '#8B5CF6',
    secondaryContainer: '#EDE9FE',
    tertiary: '#10B981',
    tertiaryContainer: '#D1FAE5',
    surface: '#FFFFFF',
    surfaceVariant: '#F1F5F9',
    background: '#F8FAFC',
    error: '#EF4444',
    errorContainer: '#FEF2F2',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#312E81',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#4C1D95',
    onTertiary: '#FFFFFF',
    onSurface: '#0F172A',
    onSurfaceVariant: '#64748B',
    onBackground: '#0F172A',
    onError: '#FFFFFF',
    outline: '#CBD5E1',
    outlineVariant: '#E2E8F0',
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#F8FAFC',
      level3: '#F1F5F9',
      level4: '#E2E8F0',
      level5: '#CBD5E1',
    },
    // Semantic tokens
    success: '#10B981',
    successContainer: '#D1FAE5',
    onSuccess: '#FFFFFF',
    warning: '#F59E0B',
    warningContainer: '#FEF3C7',
    onWarning: '#FFFFFF',
    info: '#3B82F6',
    infoContainer: '#DBEAFE',
    onInfo: '#FFFFFF',
    textMuted: '#94A3B8',
    textSecondary: '#64748B',
    inputBackground: '#F1F5F9',
    skeleton: '#E2E8F0',
  },
  fonts,
  roundness: 12,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#818CF8',
    primaryContainer: '#312E81',
    secondary: '#A78BFA',
    secondaryContainer: '#4C1D95',
    tertiary: '#34D399',
    tertiaryContainer: '#064E3B',
    surface: '#1E293B',
    surfaceVariant: '#0F172A',
    background: '#0F172A',
    error: '#F87171',
    errorContainer: '#7F1D1D',
    onPrimary: '#0F172A',
    onPrimaryContainer: '#E0E7FF',
    onSecondary: '#0F172A',
    onSecondaryContainer: '#EDE9FE',
    onTertiary: '#0F172A',
    onSurface: '#E2E8F0',
    onSurfaceVariant: '#94A3B8',
    onBackground: '#E2E8F0',
    onError: '#0F172A',
    outline: '#475569',
    outlineVariant: '#334155',
    elevation: {
      level0: 'transparent',
      level1: '#1E293B',
      level2: '#253347',
      level3: '#2D3D55',
      level4: '#334155',
      level5: '#3B4D63',
    },
    // Semantic tokens
    success: '#34D399',
    successContainer: '#064E3B',
    onSuccess: '#0F172A',
    warning: '#FBBF24',
    warningContainer: '#78350F',
    onWarning: '#0F172A',
    info: '#60A5FA',
    infoContainer: '#1E3A5F',
    onInfo: '#0F172A',
    textMuted: '#64748B',
    textSecondary: '#94A3B8',
    inputBackground: '#1E293B',
    skeleton: '#334155',
  },
  fonts,
  roundness: 12,
};

export type AppTheme = typeof lightTheme;

export function useAppTheme() {
  return useTheme<AppTheme>();
}
